export const DiscoverData = [
  {
    id: 1,
    url: "https://upload.wikimedia.org/wikipedia/commons/4/40/Pan_Am_Boeing_747-121_N732PA_Bidini.jpg",
    title: "Book Flight",
    text: "book memorable journey with our flight booking services! we are thrilled to present you fight options to suit your travel needs",
  },
  {
    id: 2,
    url: "https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg",
    title: "Book Hotels",
    text: "book memorable journey with our flight booking services! we are thrilled to present you fight options to suit your travel needs",
  },
  {
    id: 3,
    url: "https://www.cruisebooking.com/Content/site/images/CruiseImages/Articleimages/Luxury_Cruises/Article_Luxury_Cruises.webp",
    title: "Book Cruises",
    text: "book memorable journey with our flight booking services! we are thrilled to present you fight options to suit your travel needs",
  },
  {
    id: 4,
    url: "https://www.travelandleisure.com/thmb/o7LEqLUpOtf0nIm7ErqGrsVA3yo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-hotel-room-interior-bed-BOOKHOTEL0223-786eb1910382404a8806d1e1e8ed7716.jpg",
    title: "Book Family Vacation",
    text: "book memorable journey with our flight booking services! we are thrilled to present you fight options to suit your travel needs",
  },
  {
    id: 5,
    url: "https://www.aa.com/content/images/homepage/mobile-hero/en_US/Tail.png",
    title: "Book Family Vacation",
    text: "book memorable journey with our flight booking services! we are thrilled to present you fight options to suit your travel needs",
  },
  {
    id: 6,
    url: "https://www.beaches.com/blog/content/images/2020/05/Beaches-Turks-Caicos-Family-Walk-Beach.jpg",
    title: "Book Family Vacation",
    text: "book memorable journey with our flight booking services! we are thrilled to present you fight options to suit your travel needs",
  },
  {
    id: 7,
    url: "https://static01.nyt.com/images/2023/07/11/lens/11xp-cruise/11xp-cruise-articleLarge-v2.jpg?quality=75&auto=webp&disable=upscale",
    title: "Book Family Vacation",
    text: "book memorable journey with our flight booking services! we are thrilled to present you fight options to suit your travel needs",
  },
  {
    id: 8,
    url: "https://www.sterlingholidays.com/blog/wp-content/uploads/2018/06/familyvacation.jpg",
    title: "Book Family Vacation",
    text: "book memorable journey with our flight booking services! we are thrilled to present you fight options to suit your travel needs",
  },
];

export const PopularToursData = [
  {
    id: 1,
    url: "https://qph.cf2.quoracdn.net/main-qimg-edb8bbc84c33b59bbf73b2b7a839e5c3-lq",
    title: "Barcelona, Spain",
    text: "2 adults 7 days",
    price: "2400$",
  },
  {
    id: 2,
    url: "https://handluggageonly.co.uk/wp-content/uploads/2023/10/Best-Things-To-Do-In-Paris-France-7.jpg",
    title: "Paris, France",
    text: "4 adults 5 days",
    price: "3200$",
  },
  {
    id: 3,
    url: "https://a.cdn-hotels.com/gdcs/production151/d623/a8b25d0d-64d5-402f-99f5-a58f483c38c6.jpg?impolicy=fcrop&w=800&h=533&q=medium",
    title: "Rome, Italy",
    text: "3 adults 6 days",
    price: "2800$",
  },
  {
    id: 10,
    url: "https://i.natgeofe.com/n/e1601e92-9017-4b02-ad0e-72c531b09126/tbilisi-city-guide-roofs.jpg",
    title: "Tbilisi, Georgia",
    text: "3 adults 5 days",
    price: "3000$",
  },
  {
    id: 4,
    url: "https://meezabair.com/wp-content/uploads/2024/03/statue-liberty-usa.jpg",
    title: "New York City, USA",
    text: "2 adults 4 days",
    price: "1800$",
  },
  {
    id: 5,
    url: "https://www.state.gov/wp-content/uploads/2019/04/Japan-2107x1406.jpg",
    title: "Tokyo, Japan",
    text: "2 adults 8 days",
    price: "3500$",
  },
  {
    id: 6,
    url: "https://a.cdn-hotels.com/gdcs/production29/d1870/6a5ec560-bb25-11e8-970b-0242ac110006.jpg?impolicy=fcrop&w=800&h=533&q=medium",
    title: "London, UK",
    text: "3 adults 5 days",
    price: "2900$",
  },
  {
    id: 7,
    url: "https://assets.cntraveller.in/photos/622b3fdc652e69e3c9cd5372/16:9/w_1024%2Cc_limit/caleb-russell-JmuyB_LibRo-unsplash.jpg",
    title: "Sydney, Australia",
    text: "2 adults 7 days",
    price: "3800$",
  },
  {
    id: 8,
    url: "https://media.cntraveler.com/photos/655cdf1d2d09a7e0b27741b5/16:9/w_2560%2Cc_limit/Cairo%2520Egypt_GettyImages-1370918272.jpg",
    title: "Cairo, Egypt",
    text: "2 adults 6 days",
    price: "2600$",
  },
  {
    id: 9,
    url: "https://a.cdn-hotels.com/gdcs/production143/d357/42fb6908-dcd5-4edb-9f8c-76208494af80.jpg?impolicy=fcrop&w=800&h=533&q=medium",
    title: "Rio de Janeiro, Brazil",
    text: "4 adults 7 days",
    price: "4100$",
  },
];

export const BlogsData = [
  {
    id: 1,
    url: "https://greenglobaltravel.com/wp-content/uploads/6Thiksey-Maitreya.jpg",
    title: "Interesting Tibetian Traditions",
  },
  {
    id: 2,
    url: "https://cdn.britannica.com/30/153430-050-967CBF40/Eruption-Kilauea-Hawaii-Volcanoes-National-Park-1983.jpg",
    title: "Are There Volcanos In Hawaii?",
  },
  {
    id: 3,
    url: "https://happiestoutdoors.ca/wp-content/uploads/2017/01/iceland-6.jpg",
    title: "Winter in Iceland",
  },
  {
    id: 4,
    url: "https://greenglobaltravel.com/wp-content/uploads/6Thiksey-Maitreya.jpg",
    title: "Interesting Tibetian Traditions",
  },
  {
    id: 5,
    url: "https://cdn.britannica.com/30/153430-050-967CBF40/Eruption-Kilauea-Hawaii-Volcanoes-National-Park-1983.jpg",
    title: "Are There Volcanos In Hawaii?",
  },
  {
    id: 6,
    url: "https://happiestoutdoors.ca/wp-content/uploads/2017/01/iceland-6.jpg",
    title: "Winter in Iceland",
  },
];

const FlyghtsData = [
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 9,
    stop: 2,
    landing: 17,
    price: "400$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 8,
    stop: 3,
    landing: 20,
    price: "700$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 10,
    stop: 2,
    landing: 18,
    price: "400$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 8,
    stop: 3,
    landing: 21,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
  {
    url: "https://seeklogo.com/images/A/Airzena_-_Georgian_Airways-logo-30B05E0542-seeklogo.com.png",
    title: "Georgian Airlines",
    takeOff: 12,
    stop: 1,
    landing: 19,
    price: "600$",
  },
];
